# Generated by Django 4.2.5 on 2023-09-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("extracto", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("violencia", "Violencia"),
                            ("derechos_repr", "Derechos Reproductivos"),
                            ("deportes", "Deportes"),
                            ("moda", "Moda"),
                            ("ddhh", "Derechos Humanos"),
                            ("interseccionalidad", "Interseccionalidad"),
                            ("trabajo", "Trabajo"),
                            ("educacion", "Educación"),
                            ("salud", "Salud"),
                            ("seguridad", "Seguridad"),
                            ("tecnologia", "Tecnología"),
                            ("economia", "Economía"),
                            ("participacion", "Participación política"),
                        ],
                        default="tecnologia",
                        max_length=20,
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("estatus", models.IntegerField(choices=[(0, "Borrador"), (1, "Publicado")], default=0)),
                ("destacado", models.BooleanField()),
                (
                    "seccion",
                    models.IntegerField(
                        choices=[(0, "Blog"), (1, "Datoteca"), (2, "Heramientas"), (3, "Proyectos")], default=0
                    ),
                ),
                ("imagen_principal", models.ImageField(upload_to="")),
                ("imagen2", models.ImageField(blank=True, upload_to="")),
                ("imagen3", models.ImageField(blank=True, upload_to="")),
                ("imagen4", models.ImageField(blank=True, upload_to="")),
                ("imagen5", models.ImageField(blank=True, upload_to="")),
            ],
        ),
    ]
