# Generated by Django 4.2.5 on 2023-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odegiblog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autora",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="publicacion",
            name="autora",
            field=models.ManyToManyField(to="odegiblog.autora"),
        ),
    ]
