# Generated by Django 4.2.5 on 2023-09-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odegiblog", "0002_autora_publicacion_autora"),
    ]

    operations = [
        migrations.AddField(
            model_name="autora",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
