# Generated by Django 4.2.5 on 2023-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odegiblog", "0003_autora_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="publicacion",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name="publicacion",
            name="categoria",
        ),
        migrations.AddField(
            model_name="publicacion",
            name="categoria",
            field=models.ManyToManyField(to="odegiblog.categoria"),
        ),
    ]
