# Generated by Django 4.2.5 on 2023-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glosario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("termino", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("definicion", models.TextField()),
                ("estatus", models.IntegerField(choices=[(0, "Borrador"), (1, "Publicado")], default=0)),
            ],
        ),
    ]
